require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VoluntariosController do

  # This should return the minimal set of attributes required to create a valid
  # Voluntario. As you add validations to Voluntario, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VoluntariosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all voluntarios as @voluntarios" do
      voluntario = Voluntario.create! valid_attributes
      get :index, {}, valid_session
      assigns(:voluntarios).should eq([voluntario])
    end
  end

  describe "GET show" do
    it "assigns the requested voluntario as @voluntario" do
      voluntario = Voluntario.create! valid_attributes
      get :show, {:id => voluntario.to_param}, valid_session
      assigns(:voluntario).should eq(voluntario)
    end
  end

  describe "GET new" do
    it "assigns a new voluntario as @voluntario" do
      get :new, {}, valid_session
      assigns(:voluntario).should be_a_new(Voluntario)
    end
  end

  describe "GET edit" do
    it "assigns the requested voluntario as @voluntario" do
      voluntario = Voluntario.create! valid_attributes
      get :edit, {:id => voluntario.to_param}, valid_session
      assigns(:voluntario).should eq(voluntario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Voluntario" do
        expect {
          post :create, {:voluntario => valid_attributes}, valid_session
        }.to change(Voluntario, :count).by(1)
      end

      it "assigns a newly created voluntario as @voluntario" do
        post :create, {:voluntario => valid_attributes}, valid_session
        assigns(:voluntario).should be_a(Voluntario)
        assigns(:voluntario).should be_persisted
      end

      it "redirects to the created voluntario" do
        post :create, {:voluntario => valid_attributes}, valid_session
        response.should redirect_to(Voluntario.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved voluntario as @voluntario" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voluntario.any_instance.stub(:save).and_return(false)
        post :create, {:voluntario => {}}, valid_session
        assigns(:voluntario).should be_a_new(Voluntario)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voluntario.any_instance.stub(:save).and_return(false)
        post :create, {:voluntario => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested voluntario" do
        voluntario = Voluntario.create! valid_attributes
        # Assuming there are no other voluntarios in the database, this
        # specifies that the Voluntario created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Voluntario.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => voluntario.to_param, :voluntario => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested voluntario as @voluntario" do
        voluntario = Voluntario.create! valid_attributes
        put :update, {:id => voluntario.to_param, :voluntario => valid_attributes}, valid_session
        assigns(:voluntario).should eq(voluntario)
      end

      it "redirects to the voluntario" do
        voluntario = Voluntario.create! valid_attributes
        put :update, {:id => voluntario.to_param, :voluntario => valid_attributes}, valid_session
        response.should redirect_to(voluntario)
      end
    end

    describe "with invalid params" do
      it "assigns the voluntario as @voluntario" do
        voluntario = Voluntario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voluntario.any_instance.stub(:save).and_return(false)
        put :update, {:id => voluntario.to_param, :voluntario => {}}, valid_session
        assigns(:voluntario).should eq(voluntario)
      end

      it "re-renders the 'edit' template" do
        voluntario = Voluntario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voluntario.any_instance.stub(:save).and_return(false)
        put :update, {:id => voluntario.to_param, :voluntario => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested voluntario" do
      voluntario = Voluntario.create! valid_attributes
      expect {
        delete :destroy, {:id => voluntario.to_param}, valid_session
      }.to change(Voluntario, :count).by(-1)
    end

    it "redirects to the voluntarios list" do
      voluntario = Voluntario.create! valid_attributes
      delete :destroy, {:id => voluntario.to_param}, valid_session
      response.should redirect_to(voluntarios_url)
    end
  end

end
